### ISSUE TITLE
undefined method `authentcation_info when connecting

### ISSUE THREAD

**Issue by krisleech** [xaop/activecmis#9]
Disclaimer: I may be doing this wrong.

`load_config` works fine but I don't wish to use a yaml file.

```
server = ActiveCMIS::Server.new('http://localhost:8082/alfresco/service/cmis')
server = server.authenticate(:basic, 'admin', 'admin)
repo = server.repository('SOME NODE ID')
# => undefined method `authentcation_info' for Server http://localhost:8082/alfresco/service/cmis:ActiveCMIS::Server
```

The work around is to pass `nil` as a second parameter to `server.repository`.

I can see there is a mispelling of authentication [here](https://github.com/xaop/activecmis/blob/master/lib/active_cmis/server.rb#L70) but correcting it did not help.

**Comment by CloCkWeRX** [comment]
Hey @joerixaop  this is closable isn't it?
